all: affichage factorielle portee lecture

affichage: affichage.c
	gcc affichage.c -o affichage

factorielle: factorielle.c
	gcc factorielle.c -o factorielle

portee: portee.c
	gcc portee.c -o portee

lecture: lecture.c
	gcc lecture.c -o lecture

clean: 
	rm -f *.o